spring:
  mvc:
      view:
        prefix: /WEB-INF/myjsps/
        suffix: .jsp
server:
    port: 12345
logging:
    level:
        root: INFO
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
